FirebaseError: Missing or insufficient permissions. got this for reviewer dashboard... I think reviewers dont submit the papers so need of that functionality and even the registration page is irrelevant so hide those too