FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/researchsphere-46353/firestore/indexes?create_composite=ClNwcm9qZWN0cy9yZXNlYXJjaHNwaGVyZS00NjM1My9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvcGFwZXJzL2luZGV4ZXMvXxABGgoKBnVzZXJJZBABGg4KCnVwbG9hZERhdGUQAhoMCghfX25hbWVfXxAC
also correct  the logic if user selects to pay now then pop up the mock payment window if the mock payment done then only move forward and submit the paper